options:
  image:
    type: string
    default: "tengudocker/kafka-persist"
    description: |
      Default kafka persist docker image.
  topics:
    type: string
    default: ""
    description: |
      Space separated list of topics to subscribe to.